package com.codepliot.client;

import com.codepliot.config.LlmProperties;
import com.codepliot.model.LlmMessage;
import com.codepliot.model.LlmRuntimeConfig;
import com.codepliot.model.LlmToolCall;
import com.codepliot.model.LlmToolChatResponse;
import com.codepliot.model.LlmToolDefinition;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class MockLlmClient implements LlmClient {

    private final LlmProperties llmProperties;

    public MockLlmClient(LlmProperties llmProperties) {
        this.llmProperties = llmProperties;
    }

    @Override
    public String provider() {
        return "mock";
    }

    @Override
    public String generate(LlmRuntimeConfig config, String systemPrompt, String userPrompt) {
        String normalizedPrompt = userPrompt == null ? "" : userPrompt.toLowerCase();
        String providerName = config == null ? llmProperties.getProvider() : config.provider();
        if (normalizedPrompt.contains("\"patch\"") && normalizedPrompt.contains("\"risk\"")) {
            return """
                    {
                      "analysis": "Mock analysis",
                      "solution": "Mock solution",
                      "patch": "",
                      "risk": "Generated by mock provider %s"
                    }
                    """.formatted(providerName);
        }

        return """
                Mock analysis:
                1. This response is generated by the mock LLM provider.
                2. No external model request was sent.
                3. Configure a real provider on the project page to run real analysis.
                """;
    }

    @Override
    public LlmToolChatResponse chatWithTools(LlmRuntimeConfig config,
                                             List<LlmMessage> messages,
                                             List<LlmToolDefinition> tools) {
        boolean hasToolResult = messages != null && messages.stream().anyMatch(message -> "tool".equals(message.role()));
        if (hasToolResult || tools == null || tools.isEmpty()) {
            return new LlmToolChatResponse("", "stop", List.of());
        }
        String toolName = tools.stream()
                .map(LlmToolDefinition::name)
                .filter("grep"::equals)
                .findFirst()
                .orElse(tools.get(0).name());
        return new LlmToolChatResponse("", "tool_calls", List.of(
                new LlmToolCall("mock_tool_call_1", toolName, "{\"query\":\"class\",\"globPatterns\":[\"**/*.java\"],\"maxResults\":5}")
        ));
    }
}
