CREATE TABLE IF NOT EXISTS sentry_alert_event (
  id BIGINT NOT NULL COMMENT 'MyBatis-Plus ASSIGN_ID',
  sentry_organization_slug VARCHAR(128) DEFAULT NULL,
  sentry_project_slug VARCHAR(128) DEFAULT NULL,
  sentry_issue_id VARCHAR(128) DEFAULT NULL,
  sentry_event_id VARCHAR(128) DEFAULT NULL,
  sentry_alert_rule_id VARCHAR(128) DEFAULT NULL,
  sentry_alert_rule_name VARCHAR(255) DEFAULT NULL,
  fingerprint VARCHAR(512) DEFAULT NULL,
  title VARCHAR(512) DEFAULT NULL,
  level VARCHAR(32) DEFAULT NULL,
  platform VARCHAR(64) DEFAULT NULL,
  culprit VARCHAR(512) DEFAULT NULL,
  web_url VARCHAR(1024) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
  agent_task_id BIGINT DEFAULT NULL,
  dedupe_key VARCHAR(768) NOT NULL,
  raw_payload MEDIUMTEXT DEFAULT NULL,
  enriched_context MEDIUMTEXT DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_sentry_alert_event_project_issue (sentry_project_slug, sentry_issue_id),
  KEY idx_sentry_alert_event_task (agent_task_id),
  KEY idx_sentry_alert_event_dedupe (dedupe_key),
  KEY idx_sentry_alert_event_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
