package com.codepliot.llm;

import com.codepliot.llm.config.LlmProperties;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

/**
 * 本地开发用 Mock LLM 客户端。
 */
@Component
@ConditionalOnProperty(prefix = "codepilot.llm", name = "provider", havingValue = "mock", matchIfMissing = true)
public class MockLlmClient implements LlmClient {

    private final LlmProperties llmProperties;

    public MockLlmClient(LlmProperties llmProperties) {
        this.llmProperties = llmProperties;
    }

    @Override
    public String generate(String systemPrompt, String userPrompt) {
        String normalizedPrompt = userPrompt == null ? "" : userPrompt.toLowerCase();
        if (normalizedPrompt.contains("\"patch\"") && normalizedPrompt.contains("\"risk\"")) {
            return """
                    {
                      "analysis": "Mock analysis based only on the provided issue and retrieved code snippets.",
                      "solution": "Mock client does not generate a reliable patch. Review the analysis and implement changes manually.",
                      "patch": "",
                      "risk": "MockLlmClient is enabled via codepilot.llm.provider=%s, so no real model output is available."
                    }
                    """.formatted(llmProperties.getProvider());
        }

        return """
                Mock analysis result:
                - This analysis is generated by MockLlmClient.
                - It only reflects the provided issue and retrieved code snippets.
                - Cross-language relationships should be reviewed manually before applying any real code changes.
                - If more evidence is needed, retrieve additional code context.
                """;
    }
}
